# Generated by Django 4.2.6 on 2023-11-04 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentification", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="nom",
        ),
        migrations.RemoveField(
            model_name="user",
            name="prenom",
        ),
    ]
