# Generated by Django 4.2.6 on 2023-11-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentification", "0003_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
