# Generated by Django 4.2.6 on 2023-12-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentification", "0006_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.AddField(
            model_name="user",
            name="validated_at",
            field=models.DateField(default=None, null=True),
        ),
    ]
