# Generated by Django 4.2.6 on 2023-12-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentification", "0007_remove_user_is_active_user_validated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="validated_at",
            field=models.DateField(null=True),
        ),
    ]
