# Generated by Django 4.2.6 on 2023-12-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("formations", "0011_merge_20231220_2129"),
        ("authentification", "0008_alter_user_validated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="inscrit_a",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="formations.formation",
            ),
        ),
    ]
