# Generated by Django 4.2.6 on 2023-12-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentification", "0010_alter_user_inscrit_a"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="pfp",
            field=models.FileField(null=True, upload_to="pfps/"),
        ),
    ]
