# Generated by Django 4.2.6 on 2023-12-18 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("formations", "0009_alter_chapitre_module"),
        (
            "candidature",
            "0004_remove_candidature_unique_migration_host_combination_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidature",
            name="idformation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="formations.formation"
            ),
        ),
    ]
