# Generated by Django 4.2.6 on 2023-12-17 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='fichiers_cours/')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('enseignants', models.ManyToManyField(related_name='modules_enseignes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='formation',
            name='createur',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='date_fin',
        ),
        migrations.DeleteModel(
            name='InscriptionFormation',
        ),
        migrations.AddField(
            model_name='module',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formation'),
        ),
        migrations.AddField(
            model_name='cours',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.module'),
        ),
    ]
