# Generated by Django 4.2.6 on 2023-12-17 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_cours_fichier_module_remove_formation_createur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='documents/')),
                ('description', models.TextField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.cours')),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='enseignants',
        ),
        migrations.DeleteModel(
            name='Fichier',
        ),
    ]
