# Generated by Django 4.2.6 on 2023-12-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_document_remove_module_enseignants_delete_fichier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='description',
            new_name='contenu',
        ),
        migrations.RenameField(
            model_name='formation',
            old_name='titre',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='titre',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
