# Generated by Django 4.2.6 on 2023-12-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0004_rename_description_cours_contenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
