# Generated by Django 4.2.6 on 2023-12-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0005_alter_formation_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='date_debut',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='date_fin',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='debouches_professionnels',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='formation',
            name='nombre_etudiants',
            field=models.IntegerField(default=0),
        ),
    ]
