# Generated by Django 4.2.6 on 2023-12-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0006_formation_date_debut_formation_date_fin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('documentation', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.DeleteModel(
            name='Cours',
        ),
        migrations.AddField(
            model_name='module',
            name='chapitres',
            field=models.ManyToManyField(to='formations.chapitre'),
        ),
    ]
