# Generated by Django 4.2.6 on 2023-12-17 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0008_rename_documentation_chapitre_fichier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitre',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.module'),
        ),
    ]
