# Generated by Django 4.2.6 on 2023-12-18 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0009_alter_chapitre_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitre',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='formations.module'),
        ),
    ]
