# Generated by Django 4.2.6 on 2023-12-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0010_alter_chapitre_module'),
        ('formations', '0010_formation_responsable'),
    ]

    operations = [
    ]
