# Generated by Django 4.2.6 on 2023-12-19 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formations', '0012_module_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='formation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='formations.formation'),
        ),
        migrations.AlterField(
            model_name='module',
            name='responsable',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
