# Generated by Django 4.2.6 on 2023-12-20 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0013_alter_module_formation_alter_module_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitre',
            name='fichier',
            field=models.FileField(default=None, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='formations.module'),
        ),
    ]
