# Generated by Django 4.2.6 on 2023-12-22 11:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("formations", "0011_merge_20231220_2129"),
        ("formations", "0014_alter_chapitre_fichier_alter_chapitre_module"),
    ]

    operations = []
