# Generated by Django 4.2.6 on 2023-12-25 15:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("formations", "0015_merge_20231222_1247"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapitre",
            name="fichier",
        ),
        migrations.CreateModel(
            name="FichierChapitre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=80)),
                ("url", models.FileField(upload_to="utilisateur/")),
                ("date_upload", models.DateField(default=django.utils.timezone.now)),
                (
                    "chapitre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formations.chapitre",
                    ),
                ),
            ],
        ),
    ]
